server:
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(3XJkFO537HvFkUkKfZEjYeN1U8b2mVwpnRv6/wl6ZneP6odkliHkcV7A135YfXfDA6W9xeoOOD4w5zeuhqauGAj069fDmRGq89OsAUE+rA1cmIZ3bZsm80o6im4mhw09QqZrDx8oMoRvhMCsT23Adq4RUBJ7B9z3g5nSdcEmFVCkHYVB3Bg0Zb49DmDYDyzDWHqEgMYc+AAx8upoOK9yOErnkK7R/kA+omwTMk7ymlDRgZNBskXw9uUAuGl/Pa9m)
    username: ENC(lVSrqCpmTW5Z7LsDVhoNIQ==)
    password: ENC(vz6izsSjhrgiaPC/ZwLvjSOiW4F6uDanR2Kjcp7emYwC22DtClpZUMg+Z35ODtAx)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ENC(biGY1NB/OG+9fMjwd9xydQ==)
      port: 6379
      password: ENC(f/q6GpGysypGkQk/Mswp9J3L2U3SLMwp)

cloud:
  aws:
    credentials:
      access-key: ENC(SPPzrqWgyXUXVTcgjkyUpRu3M1WMigX4naC5pEWqHt0=)
      secret-key: ENC(cB07qYeqVSis0WKZqqoOsLhNc+Hes1hJnhHbBIflyGMLQRmVDLno7Ne9poRh3DGT7D1vwwKHo5Q=)
    s3:
      bucket: ENC(6V5nfAzhQgBTFIntlqAi03ssLAzppMvX)
    region:
      static: ap-northeast-2

# 프론트엔드 URL (OAuth 콜백 리다이렉트용)
app:
  frontend-url: ENC(utl1cWheQ+zZot47kM2AOKtxwd4PUW/IAIbbQLAnT1S1R4aOKPJEHg==)

# 로깅 설정
logging:
  level:
    root: INFO
    com.behcm: DEBUG